Fix missing param for updateCache
Was causing
```no-highlight
TypeError: undefined is not a function
    at /var/www/myproject/node_modules/strider-bower/lib/update-cache.js:13:14
    at /var/www/myproject/node_modules/strider-bower/lib/bower-hash.js:10:14
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
```